// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type MetaTradeType int32

const (
	MetaTradeType_Mt4 MetaTradeType = 0
	MetaTradeType_Mt5 MetaTradeType = 1
)

var MetaTradeType_name = map[int32]string{
	0: "Mt4",
	1: "Mt5",
}
var MetaTradeType_value = map[string]int32{
	"Mt4": 0,
	"Mt5": 1,
}

func (x MetaTradeType) String() string {
	return proto.EnumName(MetaTradeType_name, int32(x))
}
func (MetaTradeType) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

type MetaTradeRole int32

const (
	MetaTradeRole_Account MetaTradeRole = 0
	MetaTradeRole_Manager MetaTradeRole = 1
	MetaTradeRole_Admin   MetaTradeRole = 2
)

var MetaTradeRole_name = map[int32]string{
	0: "Account",
	1: "Manager",
	2: "Admin",
}
var MetaTradeRole_value = map[string]int32{
	"Account": 0,
	"Manager": 1,
	"Admin":   2,
}

func (x MetaTradeRole) String() string {
	return proto.EnumName(MetaTradeRole_name, int32(x))
}
func (MetaTradeRole) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

type GetPositionsRequest_QueryTimeBy int32

const (
	GetPositionsRequest_Open      GetPositionsRequest_QueryTimeBy = 0
	GetPositionsRequest_Close     GetPositionsRequest_QueryTimeBy = 1
	GetPositionsRequest_Timestamp GetPositionsRequest_QueryTimeBy = 2
)

var GetPositionsRequest_QueryTimeBy_name = map[int32]string{
	0: "Open",
	1: "Close",
	2: "Timestamp",
}
var GetPositionsRequest_QueryTimeBy_value = map[string]int32{
	"Open":      0,
	"Close":     1,
	"Timestamp": 2,
}

func (x GetPositionsRequest_QueryTimeBy) String() string {
	return proto.EnumName(GetPositionsRequest_QueryTimeBy_name, int32(x))
}
func (GetPositionsRequest_QueryTimeBy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor3, []int{3, 0}
}

type GetPositionsRequest_SortBy int32

const (
	GetPositionsRequest_OpenAsc       GetPositionsRequest_SortBy = 0
	GetPositionsRequest_OpenDesc      GetPositionsRequest_SortBy = 1
	GetPositionsRequest_CloseAsc      GetPositionsRequest_SortBy = 2
	GetPositionsRequest_CloseDesc     GetPositionsRequest_SortBy = 3
	GetPositionsRequest_LoginAsc      GetPositionsRequest_SortBy = 4
	GetPositionsRequest_LoginDesc     GetPositionsRequest_SortBy = 5
	GetPositionsRequest_TimestampAsc  GetPositionsRequest_SortBy = 6
	GetPositionsRequest_TimestampDesc GetPositionsRequest_SortBy = 7
)

var GetPositionsRequest_SortBy_name = map[int32]string{
	0: "OpenAsc",
	1: "OpenDesc",
	2: "CloseAsc",
	3: "CloseDesc",
	4: "LoginAsc",
	5: "LoginDesc",
	6: "TimestampAsc",
	7: "TimestampDesc",
}
var GetPositionsRequest_SortBy_value = map[string]int32{
	"OpenAsc":       0,
	"OpenDesc":      1,
	"CloseAsc":      2,
	"CloseDesc":     3,
	"LoginAsc":      4,
	"LoginDesc":     5,
	"TimestampAsc":  6,
	"TimestampDesc": 7,
}

func (x GetPositionsRequest_SortBy) String() string {
	return proto.EnumName(GetPositionsRequest_SortBy_name, int32(x))
}
func (GetPositionsRequest_SortBy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor3, []int{3, 1}
}

type SymbolEventMessage struct {
}

func (m *SymbolEventMessage) Reset()                    { *m = SymbolEventMessage{} }
func (m *SymbolEventMessage) String() string            { return proto.CompactTextString(m) }
func (*SymbolEventMessage) ProtoMessage()               {}
func (*SymbolEventMessage) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

type GetCommonSettingRequest struct {
}

func (m *GetCommonSettingRequest) Reset()                    { *m = GetCommonSettingRequest{} }
func (m *GetCommonSettingRequest) String() string            { return proto.CompactTextString(m) }
func (*GetCommonSettingRequest) ProtoMessage()               {}
func (*GetCommonSettingRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

type GetCommonSettingResponse struct {
}

func (m *GetCommonSettingResponse) Reset()                    { *m = GetCommonSettingResponse{} }
func (m *GetCommonSettingResponse) String() string            { return proto.CompactTextString(m) }
func (*GetCommonSettingResponse) ProtoMessage()               {}
func (*GetCommonSettingResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

type GetPositionsRequest struct {
	Login     int32                        `protobuf:"varint,1,opt,name=login" json:"login,omitempty"`
	Since     int64                        `protobuf:"varint,2,opt,name=since" json:"since,omitempty"`
	Until     int64                        `protobuf:"varint,3,opt,name=until" json:"until,omitempty"`
	SortBy    []GetPositionsRequest_SortBy `protobuf:"varint,4,rep,packed,name=sortBy,enum=pb.GetPositionsRequest_SortBy" json:"sortBy,omitempty"`
	CalProfit bool                         `protobuf:"varint,5,opt,name=calProfit" json:"calProfit,omitempty"`
}

func (m *GetPositionsRequest) Reset()                    { *m = GetPositionsRequest{} }
func (m *GetPositionsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetPositionsRequest) ProtoMessage()               {}
func (*GetPositionsRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *GetPositionsRequest) GetLogin() int32 {
	if m != nil {
		return m.Login
	}
	return 0
}

func (m *GetPositionsRequest) GetSince() int64 {
	if m != nil {
		return m.Since
	}
	return 0
}

func (m *GetPositionsRequest) GetUntil() int64 {
	if m != nil {
		return m.Until
	}
	return 0
}

func (m *GetPositionsRequest) GetSortBy() []GetPositionsRequest_SortBy {
	if m != nil {
		return m.SortBy
	}
	return nil
}

func (m *GetPositionsRequest) GetCalProfit() bool {
	if m != nil {
		return m.CalProfit
	}
	return false
}

type GetPricesRequest struct {
	// login和group 任意一个是有意义的值，都会返回组中启用且包含加点的报价，否则会返回manager下所有的报价
	Login int32  `protobuf:"varint,1,opt,name=login" json:"login,omitempty"`
	Group string `protobuf:"bytes,2,opt,name=group" json:"group,omitempty"`
	// 查询报价，如果不填写，则会返回，所有可
	Symbols []string `protobuf:"bytes,3,rep,name=symbols" json:"symbols,omitempty"`
}

func (m *GetPricesRequest) Reset()                    { *m = GetPricesRequest{} }
func (m *GetPricesRequest) String() string            { return proto.CompactTextString(m) }
func (*GetPricesRequest) ProtoMessage()               {}
func (*GetPricesRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

func (m *GetPricesRequest) GetLogin() int32 {
	if m != nil {
		return m.Login
	}
	return 0
}

func (m *GetPricesRequest) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *GetPricesRequest) GetSymbols() []string {
	if m != nil {
		return m.Symbols
	}
	return nil
}

type ConfigServiceRequest struct {
	SecretName string        `protobuf:"bytes,1,opt,name=secretName" json:"secretName,omitempty"`
	SecretKey  string        `protobuf:"bytes,2,opt,name=secretKey" json:"secretKey,omitempty"`
	Server     string        `protobuf:"bytes,3,opt,name=server" json:"server,omitempty"`
	MtType     MetaTradeType `protobuf:"varint,4,opt,name=mtType,enum=pb.MetaTradeType" json:"mtType,omitempty"`
	MtRole     MetaTradeRole `protobuf:"varint,5,opt,name=mtRole,enum=pb.MetaTradeRole" json:"mtRole,omitempty"`
}

func (m *ConfigServiceRequest) Reset()                    { *m = ConfigServiceRequest{} }
func (m *ConfigServiceRequest) String() string            { return proto.CompactTextString(m) }
func (*ConfigServiceRequest) ProtoMessage()               {}
func (*ConfigServiceRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{5} }

func (m *ConfigServiceRequest) GetSecretName() string {
	if m != nil {
		return m.SecretName
	}
	return ""
}

func (m *ConfigServiceRequest) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

func (m *ConfigServiceRequest) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *ConfigServiceRequest) GetMtType() MetaTradeType {
	if m != nil {
		return m.MtType
	}
	return MetaTradeType_Mt4
}

func (m *ConfigServiceRequest) GetMtRole() MetaTradeRole {
	if m != nil {
		return m.MtRole
	}
	return MetaTradeRole_Account
}

func init() {
	proto.RegisterType((*SymbolEventMessage)(nil), "pb.SymbolEventMessage")
	proto.RegisterType((*GetCommonSettingRequest)(nil), "pb.GetCommonSettingRequest")
	proto.RegisterType((*GetCommonSettingResponse)(nil), "pb.GetCommonSettingResponse")
	proto.RegisterType((*GetPositionsRequest)(nil), "pb.GetPositionsRequest")
	proto.RegisterType((*GetPricesRequest)(nil), "pb.GetPricesRequest")
	proto.RegisterType((*ConfigServiceRequest)(nil), "pb.ConfigServiceRequest")
	proto.RegisterEnum("pb.MetaTradeType", MetaTradeType_name, MetaTradeType_value)
	proto.RegisterEnum("pb.MetaTradeRole", MetaTradeRole_name, MetaTradeRole_value)
	proto.RegisterEnum("pb.GetPositionsRequest_QueryTimeBy", GetPositionsRequest_QueryTimeBy_name, GetPositionsRequest_QueryTimeBy_value)
	proto.RegisterEnum("pb.GetPositionsRequest_SortBy", GetPositionsRequest_SortBy_name, GetPositionsRequest_SortBy_value)
}

func init() { proto.RegisterFile("types.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 500 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x63, 0x3b, 0x71, 0xea, 0x49, 0x53, 0x6d, 0x97, 0x08, 0x0c, 0x42, 0x95, 0xf1, 0xc9,
	0xf4, 0x10, 0x89, 0x52, 0xb8, 0xa7, 0x01, 0xf5, 0x00, 0x81, 0xb2, 0xc9, 0x81, 0xab, 0xe3, 0x4e,
	0xad, 0x95, 0xec, 0x5d, 0xb3, 0xbb, 0x89, 0xe4, 0x2b, 0x8f, 0xc6, 0xbb, 0xf0, 0x1e, 0x68, 0xd7,
	0xee, 0x1f, 0xfe, 0x48, 0xdc, 0xfc, 0xfb, 0xbe, 0x6f, 0x66, 0xe4, 0x19, 0x1b, 0x26, 0xa6, 0x6d,
	0x50, 0xcf, 0x1b, 0x25, 0x8d, 0xa4, 0x7e, 0xb3, 0x4d, 0x67, 0x40, 0xd7, 0x6d, 0xbd, 0x95, 0xd5,
	0xfb, 0x3d, 0x0a, 0xb3, 0x42, 0xad, 0xf3, 0x12, 0xd3, 0xa7, 0xf0, 0xe4, 0x12, 0xcd, 0x52, 0xd6,
	0xb5, 0x14, 0x6b, 0x34, 0x86, 0x8b, 0x92, 0xe1, 0xb7, 0x1d, 0x6a, 0x93, 0x3e, 0x83, 0xf8, 0x6f,
	0x4b, 0x37, 0x52, 0x68, 0x4c, 0x7f, 0xfa, 0xf0, 0xe8, 0x12, 0xcd, 0x95, 0xd4, 0xdc, 0x70, 0x29,
	0x74, 0x5f, 0x43, 0x67, 0x30, 0xaa, 0x64, 0xc9, 0x45, 0xec, 0x25, 0x5e, 0x36, 0x62, 0x1d, 0x58,
	0x55, 0x73, 0x51, 0x60, 0xec, 0x27, 0x5e, 0x16, 0xb0, 0x0e, 0xac, 0xba, 0x13, 0x86, 0x57, 0x71,
	0xd0, 0xa9, 0x0e, 0xe8, 0x5b, 0x08, 0xb5, 0x54, 0xe6, 0xa2, 0x8d, 0x87, 0x49, 0x90, 0x1d, 0x9d,
	0x9d, 0xcc, 0x9b, 0xed, 0xfc, 0x1f, 0xa3, 0xe6, 0x6b, 0x97, 0x62, 0x7d, 0x9a, 0x3e, 0x87, 0xa8,
	0xc8, 0xab, 0x2b, 0x25, 0x6f, 0xb8, 0x89, 0x47, 0x89, 0x97, 0x1d, 0xb0, 0x7b, 0x21, 0x7d, 0x05,
	0x93, 0x2f, 0x3b, 0x54, 0xed, 0x86, 0xd7, 0x78, 0xd1, 0xd2, 0x03, 0x18, 0x7e, 0x6e, 0x50, 0x90,
	0x01, 0x8d, 0x60, 0xb4, 0xac, 0xa4, 0x46, 0xe2, 0xd1, 0x29, 0x44, 0xd6, 0xd6, 0x26, 0xaf, 0x1b,
	0xe2, 0xa7, 0xdf, 0x3d, 0x08, 0xbb, 0x19, 0x74, 0x02, 0x63, 0x1b, 0x5f, 0xe8, 0x82, 0x0c, 0xe8,
	0x21, 0x1c, 0x58, 0x78, 0x87, 0xba, 0x20, 0x9e, 0x25, 0x57, 0x6f, 0x3d, 0xdf, 0xb6, 0x70, 0xe4,
	0xcc, 0xc0, 0x9a, 0x1f, 0xed, 0x02, 0xac, 0x39, 0xb4, 0xa6, 0x23, 0x67, 0x8e, 0x28, 0x81, 0xc3,
	0xbb, 0x71, 0x36, 0x10, 0xd2, 0x63, 0x98, 0xde, 0x29, 0x2e, 0x34, 0x4e, 0xbf, 0x02, 0xb1, 0xef,
	0xae, 0x78, 0x81, 0xff, 0xdf, 0x71, 0xa9, 0xe4, 0xae, 0x71, 0x3b, 0x8e, 0x58, 0x07, 0x34, 0x86,
	0xb1, 0x76, 0x47, 0xd7, 0x71, 0x90, 0x04, 0x59, 0xc4, 0x6e, 0x31, 0xfd, 0xe1, 0xc1, 0x6c, 0x29,
	0xc5, 0x0d, 0x2f, 0xd7, 0xa8, 0xf6, 0xbc, 0xc0, 0xdb, 0xf6, 0x27, 0x00, 0x1a, 0x0b, 0x85, 0xe6,
	0x53, 0x5e, 0xa3, 0x9b, 0x11, 0xb1, 0x07, 0x8a, 0x5d, 0x74, 0x47, 0x1f, 0xb0, 0xed, 0x87, 0xdd,
	0x0b, 0xf4, 0x31, 0x84, 0x1a, 0xd5, 0x1e, 0x95, 0xbb, 0x6a, 0xc4, 0x7a, 0xa2, 0x2f, 0x21, 0xac,
	0xcd, 0xa6, 0x6d, 0x30, 0x1e, 0x26, 0x5e, 0x76, 0x74, 0x76, 0x6c, 0xcf, 0xba, 0x42, 0x93, 0x6f,
	0x54, 0x7e, 0x8d, 0xd6, 0x60, 0x7d, 0xa0, 0x8b, 0x32, 0x59, 0xa1, 0x3b, 0xe3, 0x9f, 0x51, 0x6b,
	0xb0, 0x3e, 0x70, 0xfa, 0x02, 0xa6, 0xbf, 0xf5, 0xa0, 0x63, 0x08, 0x56, 0xe6, 0x9c, 0x0c, 0xba,
	0x87, 0x37, 0xc4, 0x3b, 0x3d, 0x7f, 0x10, 0xb1, 0x35, 0xf6, 0x98, 0x8b, 0xa2, 0x90, 0x3b, 0x61,
	0xc8, 0xc0, 0xc2, 0x2a, 0x17, 0x79, 0x89, 0x8a, 0x78, 0xf6, 0x5b, 0x58, 0x5c, 0xd7, 0x5c, 0x10,
	0x7f, 0x1b, 0xba, 0xff, 0xe6, 0xf5, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x71, 0xad, 0x17, 0x6b,
	0x46, 0x03, 0x00, 0x00,
}
